### ISSUE TITLE
PHP 5.6 does not work with SS4 upgade.

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-memberprofiles#141]
Currently, PHP 5.6 is getting an exception in Travis and gets a hard white screen in my manual testing of the confirmation.

Travis:
https://travis-ci.org/symbiote/silverstripe-memberprofiles/jobs/373767590

```
7.01s$ vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
PHP Parse error:  syntax error, unexpected 'ader' (T_STRING) in /home/travis/build/symbiote/silverstripe-memberprofiles/vendor/silverstripe/framework/tests/php/Core/Manifest/ConfigManifestTest.php on line 22
Parse error: syntax error, unexpected 'ader' (T_STRING) in /home/travis/build/symbiote/silverstripe-memberprofiles/vendor/silverstripe/framework/tests/php/Core/Manifest/ConfigManifestTest.php on line 22
The command "vendor/bin/phpunit" exited with 255.
```

**Comment by nglasl** [comment]
This module is currently listed as PHP `>=7.0.0` (I assume due to this issue), so this no longer looks to be a problem. PHP 5.6 is EOL later this year, however if somebody is depending on PHP 5.6 for this, please do let us know and/or put through a PR. It may only be a few simple changes to get it working!
