### ISSUE TITLE
Blog profile image doesnt change or upload image

### ISSUE THREAD

**Issue by liamchowneydev** [symbiote/silverstripe-memberprofiles#147]
If a user is registering or editing their profile it doesnt error but it doesnt work.  The image doesnt get uploaded to the assets folder or save to a member.

Please can I have some help with this?

**Comment by nglasl** [comment]
Hi @liamchowneydev, similar to https://github.com/symbiote/silverstripe-memberprofiles/issues/148 could you please add some steps on how to reproduce this? I'm keen to get to the bottom of both issues at the same time. It's possible this one is a validation error, but perhaps the error isn't displaying as expected?

**Comment by liamchowneydev** [comment]
Hi 😊 

 

I literally didn’t do anything that’s not “out of the box” I installed the module to learn it and ended up not using it because of this. When you edit your profile you cant change/upload a profile image. A users profile gets an image field from the blog module otherwise it doesn’t have an image field from a Silverstripe installation.

 

I cant remember the exact steps because this was ages ago but all I had was firstname, surname, password, profile image as fields

 

Kind regards

 

Liam Chowney

Web Developer

**Comment by nglasl** [comment]
Thanks @liamchowneydev, I'll spin this up and take a peek. I appreciate the issue lodged even though you didn't end up using it.

**Comment by nglasl** [comment]
Hey @liamchowneydev, I've just given things a test and encountered a separate error that looks specific to 4.3.0 https://github.com/symbiote/silverstripe-memberprofiles/pull/157. However once I resolved this, and added the fields you mentioned above (e.g. profile picture), I didn't have any issues. Upon submitting the form with changes, I get:

`Your profile has been updated.`

I can also confirm that the profile picture is updating as expected, the file gets uploaded and written to the member as expected. I can only assume this problem is specific to the blog module and how it's doing something (or perhaps there's something else in between). It's also worth removing the blog module next time to see if that resolves your problem. I'm going to close this for now, but if you do start using the module again and still encounter this, please provide some more information (e.g. code you're using for the profile picture field) and I'll be happy to take another look.

The issue I mentioned above is currently resolved in a PR and will be merged back to master soon.
