### ISSUE TITLE
Saving many_many relations

### ISSUE THREAD

**Issue by camexapps** [symbiote/silverstripe-memberprofiles#150]
Hi there, (this might be a feature not a bug..)

I have a many_many relation on my Members. Although I can get it to show up and make it editable etc via the form settings, it appears that the relation is not saved. I guess this is a limitation, and without custom modifications it would not be possible.

What I did as a workaround was use the Profile Form (for example) and used the extension points to update the Form Action. 

eg:

```php
public function updateProfileForm(Form $form)
    {
        $saveAction = new FieldList(
            new FormAction('customSave', 'Save')
        );
        $form->setActions($saveAction);
    } 
```

I copied the existing Form Action (save) code and then modified the new code to suit. I suspect this is the current way to achieve it?

Cheers

**Comment by nglasl** [comment]
Hi @camexapps, I believe that's the correct approach. This form attempts to write back into the member object https://github.com/symbiote/silverstripe-memberprofiles/blob/f31132908d6af8383d443741a89e813d21258b74/src/Pages/MemberProfilePageController.php#L279. However, many many relationships are a special case because they're not just a simple "update x to y". If you have any other questions or stumble across anything further on this, please let us know.
